version: '3'

services:
  nginx:
    container_name: teste-spring-nginx
    image: nginx:1.13
    restart: always
    ports:
      - 80:80    
      - 443:443
    volumes:
    # proxy reverso
      - ./nginx/conf.d:/etc/nginx/conf.d
      
  mysql:
    container_name: teste-spring-mysql
    image: mysql:5.7
    restart: always 
    ports:
      - 3306:3306
      - 33060:33060
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      # Volume dos dados 
      - ./dados:/var/lib/mysql    
      
  admin:
    container_name: teste-spring-admin
    image: nazarpc/phpmyadmin
    restart: always
    depends_on:
      - mysql
    links:
      - mysql:mysql
    ports:
      - 8082:80    
      
  app:
    container_name: teste-spring-app        
    build: ./teste-sts-docker-mysql
    restart: always
    working_dir: /app
    volumes:
      - ./teste-sts-docker-mysql:/app
      - ~/.m2:/root/.m2
    expose:
      - 8080
    #ports:
    #  - 8080:8080
    command: mvn clean spring-boot:run
    depends_on:
      - nginx
      - mysql
      - admin